// flow-typed signature: ed28b7b1809affc909b7800fc5ab7836
// flow-typed version: <<STUB>>/reload_v2.2.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reload/expressSampleApp/server' {
  declare module.exports: any;
}

declare module 'reload/lib/reload-client' {
  declare module.exports: any;
}

declare module 'reload/lib/reload-server' {
  declare module.exports: any;
}

declare module 'reload/lib/reload' {
  declare module.exports: any;
}

declare module 'reload/test/reload.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reload/expressSampleApp/server.js' {
  declare module.exports: $Exports<'reload/expressSampleApp/server'>;
}
declare module 'reload/index' {
  declare module.exports: $Exports<'reload'>;
}
declare module 'reload/index.js' {
  declare module.exports: $Exports<'reload'>;
}
declare module 'reload/lib/reload-client.js' {
  declare module.exports: $Exports<'reload/lib/reload-client'>;
}
declare module 'reload/lib/reload-server.js' {
  declare module.exports: $Exports<'reload/lib/reload-server'>;
}
declare module 'reload/lib/reload.js' {
  declare module.exports: $Exports<'reload/lib/reload'>;
}
declare module 'reload/test/reload.test.js' {
  declare module.exports: $Exports<'reload/test/reload.test'>;
}
