// flow-typed signature: 2bf63ce6918e4689862881010a6ec56b
// flow-typed version: <<STUB>>/sass-glob-importer_v1.0.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-glob-importer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-glob-importer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sass-glob-importer/lib/index' {
  declare module.exports: any;
}

declare module 'sass-glob-importer/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sass-glob-importer/lib/index.js' {
  declare module.exports: $Exports<'sass-glob-importer/lib/index'>;
}
declare module 'sass-glob-importer/test.js' {
  declare module.exports: $Exports<'sass-glob-importer/test'>;
}
