// flow-typed signature: e5ff19437fed07dcad2a5c31235720d5
// flow-typed version: <<STUB>>/stylelint-formatter-table_v1.0.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-formatter-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-formatter-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-formatter-table/index' {
  declare module.exports: $Exports<'stylelint-formatter-table'>;
}
declare module 'stylelint-formatter-table/index.js' {
  declare module.exports: $Exports<'stylelint-formatter-table'>;
}
