// flow-typed signature: f662a36a8bc12ee47562bbb75ce61e15
// flow-typed version: <<STUB>>/@namics/stylelint-bem_v3.1.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@namics/stylelint-bem'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@namics/stylelint-bem' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@namics/stylelint-bem/index' {
  declare module.exports: $Exports<'@namics/stylelint-bem'>;
}
declare module '@namics/stylelint-bem/index.js' {
  declare module.exports: $Exports<'@namics/stylelint-bem'>;
}
